### ISSUE TITLE
Missing mame_libretro, mame2010_libretro, and mame2015_libretro

### ISSUE THREAD

**Issue by CFTBL** [zach-morris/kodi_libretro_buildbot_game_addons#12]
I'm not sure if this is a bug or a feature request. The "Kodi Libretro Buildbot Game Addons LE ARMHF" repository includes add-on emulators for mame2000_libretro, mame2003_libretro, and mame2003_plus_libretro... but not mame_libretro, mame2010_libretro, and mame2015_libretro (even though those add-on emulators are listed as "working" in this repository's README.md). One of them in particular, mame_libretro, is probably important. It represents the most current MAME version (and it might be more compatible with IAGL's "MAME - Multiple Arcade Machine Emulator" list). Ideally though, all of them should be included in the Kodi Libretro Buildbot Game Addons LE ARMHF repository if they're working.

**Comment by zach-morris** [comment]
mame_libretro is purposefully not included - unfortunately any cores larger than 100MB are too large for a github repository.  I think mame is the only one currently that is that large.  The other mame versions would be included, but i don't see them in the libretro buildbot for armhf, see the directory [here](https://buildbot.libretro.com/nightly/linux/armhf/latest/).

**Comment by JGoutin** [comment]
It is likely possible to store files up to 2 GB for free on GitHub with Git LFS: [GitHub Documentation, Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)
