### ISSUE TITLE
Buildbot for UWP 

### ISSUE THREAD

**Issue by mario-j-moreira** [zach-morris/kodi_libretro_buildbot_game_addons#13]
Hi Zach,
i've tested Windows X64 package on a Xbox Series X but without luck, any chance this could be built for UWP?

Thanks,
chapas

**Comment by zach-morris** [comment]
I dont see a specific place in the buildbot for UWP cores:
https://buildbot.libretro.com/nightly/windows/

Can you download cores from within Retroarch on the Xbox Series X?

**Comment by mario-j-moreira** [comment]
That's precisely my question the buildbot can do the build for UWP as well?
I'm trying to use IAGL inside Kodi (from the XBox) as I do on Windows (which works perfectly).

**Comment by zach-morris** [comment]
I dont think this is possible right now, due to permissions in XBOX preventing loading external/binary addons.  They have to be part of the application when it's installled

**Comment by mario-j-moreira** [comment]
I understand what you're saying, I thought it would be possible since its running inside Kodi (at least appears to be inside). Oh well, I guess we can close this one.
