### ISSUE TITLE
Nightly Builds aren't being built for ARMHF

### ISSUE THREAD

**Issue by CFTBL** [zach-morris/kodi_libretro_buildbot_game_addons#14]
I'd open this issue for the libretro buildbot people, but I'm not exactly sure how to do that. The issue is this:  The "nightly" armhf cores  on buildbot.libretro.com (https://buildbot.libretro.com/nightly/linux/armhf/latest/) aren't getting built. That means if you're on a Raspberry Pi 4 and you install cores from kodi_libretro_buildbot_game_addons as as suggested in this repo's readme, the "nightly" cores you get are about 2.5 years old. For now, as a workaround on RPi 4, it seems best to get updated cores via RetroArch's online updater and copy each .so file to the appropriate add-on folder in Kodi.

**Comment by zach-morris** [comment]
Interesting.  Yes I see that the buildbot itself has very old cores in it.

But if retroarch is getting updated cores, it must be getting them from somewhere.
What does retroarch settings say for Config>Network>Updater>Buildbot Cores URL?

**Comment by CFTBL** [comment]
I just opened the following issue on RetroArch's github page...
```
"Nightly" Libretro Buildbot cores for armhf and armv7-neon-hf are 2.5 years old
```
It appears that the "nightly" builds at https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/ and https://buildbot.libretro.com/nightly/linux/armhf/latest/ aren't getting built (at least according to their  timestamps). If those timestamps are accurate, it means anytime you use RetroArch's online updater to update cores on a Raspberry Pi 4, you're getting cores that are 2.5 years old.

**Comment by zach-morris** [comment]
Bummer.  We'll i'll follow the issue and see where it leads

**Comment by 03stevensmi** [comment]
I found out where the armhf builds are:
https://github.com/christianhaitian/retroarch-cores

It's officially mentioned here and why...
https://github.com/libretro/RetroArch/issues/15154
FYI... There SAFE & FINE!

Could you please re-direct your build repo to this link please?

**Comment by zach-morris** [comment]
The official kodi repo may be better for this at this point:
https://mirrors.kodi.tv/addons/omega/
I see they're building armv7 and aarch64

**Comment by nerozzero5** [comment]
> The official kodi repo may be better for this at this point: https://mirrors.kodi.tv/addons/omega/ I see they're building armv7 and aarch64

still old fbneo version , regards
