### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by JGoutin** [zach-morris/kodi_libretro_buildbot_game_addons#15]
Hello,

There is no License file with this repository. Please add one.

I would like to package this repository add-on for Fedora to provides games add-ons additionally to the `game.libretro` add-on I am packaging too.

Thanks.

**Comment by zach-morris** [comment]
License should be defined in each built addon (ref [here](https://github.com/zach-morris/kodi_libretro_buildbot_game_addons/blob/main/build_and_update_addons.py#L172)).  There isn't a blanked license for all since they are different.

The license shows up in the addon.xml like this as an example:
```
...
  </extension>
  <extension point="xbmc.addon.metadata">
    <summary lang="en_GB">Sinclair - ZX 81 (EightyOne)</summary>
    <description lang="en_GB">Emulator for ZX81 by Michael D Wynne[CR]Supported files: p|tzx|t81[CR][CR]Game Addon Notes: [1] Amstrad have kindly given their permission for the redistribution|[^] of their copyrighted material but retain that copyright.</description>
    <license>GPLv3</license>
    <platform>all</platform>
    <source>http://buildbot.libretro.com/nightly/linux/x86_64/latest/81_libretro.so.zip</source>
    <news>Built from libretro buildbot commit fa3e2f66 (2023-07-21)</news>
    ...
```

**Comment by JGoutin** [comment]
I am looking for the license of the `repository.kodi_libretro_buildbot_game_addons` add-on itself. (The content I want to package is https://github.com/zach-morris/kodi_libretro_buildbot_game_addons/raw/main/repository.kodi_libretro_buildbot_game_addons.zip)

**Comment by zach-morris** [comment]
Hmm.  Well I'm not a lawyer, I'm not sure how I can make a blanket license for a repository of files with different licenses.  I don't consider there to be any particular license on that file.  The repository itself points to the [addons.xml](https://raw.githubusercontent.com/zach-morris/kodi_libretro_buildbot_game_addons/main/addons.xml) file, which contains the individual licenses.

**Comment by JGoutin** [comment]
The license apply only to what is redistributed (in that case, your repository add-on). Licenses of add-ons that your repository contains is not relevant if I build a package with only the repository plugin itself.

---
I can help you to choose a license.

There is some "ready to use" licenses that you can use for this. 

For instance, If you just want something permissive and simple, you can use the [MIT](https://choosealicense.com/licenses/mit/) license.

If you want more choices, this can help:
* https://choosealicense.com/
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Just put a `LICENSE.txt` file inside your repo with the license you selected and that's it.

**Comment by zach-morris** [comment]
OK, license.txt was added and readme updated [here](https://github.com/zach-morris/kodi_libretro_buildbot_game_addons#licenses)
